### ISSUE TITLE
Other types of queries planned (nearest, subtract, contained intersection)?

### ISSUE THREAD

**Issue by endrebak** [lh3/cgranges#2]
Thanks for the library. 

I am wondering whether you have other types of queries planned. GRanges allows for many kinds of genomic queries, such as finding the nearest interval and so on.

**Comment by lh3** [comment]
Not initially planned, but I may implement those. It should not take much time. I don't use GRanges, so I am not familiar with other types queries. I understand "contained". That can be done by a plain binary search. Could you describe "nearest" and "subtract" in detail? For example, for "nearest", do you want to get the nearest ONE interval, or a list of intervals in the order of their distances to the query interval (harder)? What about "subtract"? There is also the question about an iterator interface. Doable of course, but a little complicated.

Thanks.

**Comment by endrebak** [comment]
Do not do it for my sake! I do not need it, I was just wondering because I have to describe alternatives to pyranges in my pyranges paper.

Here are descriptions of the functionality:
https://bedtools.readthedocs.io/en/latest/content/tools/subtract.html
https://bedtools.readthedocs.io/en/latest/content/tools/closest.html

Contained/containment is an overlap query where the query is contained completely within the hit.

I refer you to the bedtools docs because they give a more rigorous description than I could.

**Comment by lh3** [comment]
I do want to make cgranges useful, which needs to have these additional functionality. I may come back to this when I have other things at hand sorted out. Thanks!

**Comment by endrebak** [comment]
Okay, nice. I think that for nearest it makes sense to find the k-nearest intervals, where k is specified by the user, not all of them. Would also be nice if you could report the distances. And that you could choose to not get overlapping features (distance 0).

Note that nearest needs to take strand into account because you often want the first upstream or first downstream.
