### ISSUE TITLE
Preprint/paper on CRanges planned?

### ISSUE THREAD

**Issue by endrebak** [lh3/cgranges#3]
I am very interested in wrapping this library in Cython and implementing functionality to avoid the Python overhead by allowing for batch queries. This is because I might want to use CRanges in my PyRanges library.

1) is that okay with you?
2) if so, how should I cite cranges?

**Comment by lh3** [comment]
Not preprint planned immediately. If I want to write one, at least I need to implement some other operations such as those you described in #2. For now, URL is the only possible citation.

Although I have a preliminary cython binding in the "python" directory, I am not good at cython or python in general. It is great that you are interested. Please feel free to work on a separate cython binding if you like. I won't publish my preliminary binding in PyPI. It is just for a reference.

**Comment by lh3** [comment]
BTW, see also my comment on AIList in #1.

**Comment by endrebak** [comment]
Thanks. It is not first on my todo-list, but it is something I would be interested in doing eventually.

You or others: feel free to ping me if you want to collaborate on Cython bindings.

**Comment by endrebak** [comment]
Interesting about the AI-list. I should perhaps implement a version on my own :)

And thanks for pointing out that std::sort is faster than qsort. Perhaps I can get a nice speed up just by changing compilers and two function-calls.
